# Generated by Django 4.2.7 on 2023-12-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='detail1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail1', to='account.userdetail', verbose_name='お仕事プロフィール1(デフォルト)'),
        ),
    ]
