# Generated by Django 4.2.7 on 2023-12-11 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_detail1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='detail1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='detail2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='detail3',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='label_select',
            field=models.CharField(choices=[('detail1', 'プロフィール1(デフォルト)'), ('detail2', 'プロフィール2'), ('detail3', 'プロフィール3')], default=1, max_length=50, verbose_name='ラベル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
