# Generated by Django 4.2.7 on 2023-12-06 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='プロジェクトのタイトル')),
                ('about', models.TextField(verbose_name='このプロジェクトについて')),
                ('deadline_datetime', models.DateTimeField(verbose_name='締め切り日時')),
                ('reference_image1', models.ImageField(blank=True, null=True, upload_to='references', verbose_name='参考画像1')),
                ('reference_image2', models.ImageField(blank=True, null=True, upload_to='references', verbose_name='参考画像2')),
                ('reference_image3', models.ImageField(blank=True, null=True, upload_to='references', verbose_name='参考画像3')),
                ('reference_movie1', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考動画1')),
                ('reference_movie2', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考動画2')),
                ('reference_movie3', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考動画3')),
                ('reference_music1', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考音源1')),
                ('reference_music2', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考音源2')),
                ('reference_music3', models.FileField(blank=True, null=True, upload_to='references', verbose_name='参考音源3')),
                ('reference_url1', models.URLField(blank=True, null=True, verbose_name='参考URL1')),
                ('reference_url2', models.URLField(blank=True, null=True, verbose_name='参考URL2')),
                ('reference_url3', models.URLField(blank=True, null=True, verbose_name='参考URL3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='プロジェクトを登録した日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='プロジェクトの詳細を更新した時間')),
                ('contractor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_user', to=settings.AUTH_USER_MODEL, verbose_name='受注者')),
                ('contractor_users', models.ManyToManyField(blank=True, related_name='contractor_users', to=settings.AUTH_USER_MODEL, verbose_name='受注者のサポーター')),
                ('orderer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderer_user', to=settings.AUTH_USER_MODEL, verbose_name='発注者')),
                ('orderer_users', models.ManyToManyField(blank=True, related_name='orderer_users', to=settings.AUTH_USER_MODEL, verbose_name='発注者のサポーター')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('content', models.TimeField(verbose_name='本文')),
                ('deadline_datetime', models.DateTimeField(verbose_name='締め切り日時')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='タスクを追加した日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='プロジェクト')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ToDoのタイトル')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='ToDoを追加した日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='関連するプロジェクト')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task', verbose_name='関連するタスク')),
            ],
        ),
    ]
