# Generated by Django 4.2.7 on 2023-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, help_text='todoを完了させたらTrue'),
        ),
    ]
