# Generated by Django 4.2.7 on 2023-12-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_todo_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False, help_text='プロジェクトが完了したらTrue'),
        ),
    ]
