# Generated by Django 4.2.7 on 2023-12-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_detail1_remove_customuser_detail2_and_more'),
        ('project', '0005_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feedback_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userdetail', verbose_name='受注した人が設定したフィードバックルール'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='プロジェクトを確認してもらえたらTrue'),
        ),
    ]
