# Generated by Django 4.2.7 on 2023-12-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='タスクを更新した日時'),
        ),
    ]
